name: wine_quality_predictor
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip>=23
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - ipython
  - jupyter=1.0
  - jupyterlab=4.0
  - ipykernel
  - pandera
  - pip
