name: wine_quality_predictor
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip>=23
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - ipython
  - jupyter=1.0
  - jupyterlab=4.0
  - ipykernel
  - pandera
  - pip
  - conda-lock=>3.0.4
  #- quarto>=1.4
  - click>=8.0
  - requests>=2.28
  - tectonic
  # - pip:
  #     - quarto-cli>=1.4
  
