name: wine_quality_predictor
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.1
  - numpy=1.26
  - matplotlib=3.8
  - seaborn=0.13
  - scikit-learn=1.3
  - jupyter=1.0
  - jupyterlab=4.0
  - ipykernel
  - pip
